name: Chintito Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: |
          ls -la
          uname -r

      - name: Run script
        run: |
          echo "Hello GitHub Actions: ${{ secrets.COMPANY }}"
